"""
Submit Ramulator2 jobs to SLURM (or run them locally), using the run.sh
launcher generated by setup_run.py.

Reads run.sh from the current working directory.
"""

import argparse
import os
import time
from concurrent.futures import ThreadPoolExecutor


# ----------------------------------------------------------------------
# Run-time knobs (override via env vars if needed)
# ----------------------------------------------------------------------
SLURM_USERNAME       = os.environ.get("SLURM_USERNAME", "$USER")
MAX_SLURM_JOBS       = int(os.environ.get("MAX_SLURM_JOBS", "1000"))
SLURM_SUBMIT_DELAY   = float(os.environ.get("SLURM_SUBMIT_DELAY", "0.1"))   # seconds
SLURM_RETRY_DELAY    = float(os.environ.get("SLURM_RETRY_DELAY", "60"))     # seconds
PERSONAL_RUN_THREADS = int(os.environ.get("PERSONAL_RUN_THREADS", "40"))


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        prog="ExecuteRunScript",
        description="Submit jobs from run.sh to SLURM, or run them locally.",
    )
    p.add_argument("-s", "--slurm", action="store_true",
                   help="Submit each line as an sbatch command (default: run locally).")
    return p.parse_args()


def check_running_jobs() -> int:
    """Return the number of queued/running SLURM jobs for this user."""
    return int(os.popen(f"squeue -u {SLURM_USERNAME} -h | wc -l").read())


def run_slurm(commands):
    for cmd in commands:
        while check_running_jobs() >= MAX_SLURM_JOBS:
            print(f"[INFO] Maximum SLURM job limit ({MAX_SLURM_JOBS}) reached. "
                  f"Retrying in {SLURM_RETRY_DELAY:.0f} seconds.")
            time.sleep(SLURM_RETRY_DELAY)
        os.system(cmd)
        time.sleep(SLURM_SUBMIT_DELAY)


def run_personal(commands):
    def run_one(cmd):
        os.system(f'echo "Running: {cmd}"')
        os.system(cmd)

    with ThreadPoolExecutor(max_workers=PERSONAL_RUN_THREADS) as executor:
        # list() forces eager evaluation so exceptions surface.
        list(executor.map(run_one, commands))


def main():
    args = parse_args()

    if not os.path.exists("run.sh"):
        raise SystemExit(
            "[ERROR] run.sh not found in the current working directory. "
            "Did setup_run.py run successfully?"
        )

    with open("run.sh", "r") as f:
        # Skip blank lines and the shebang.
        lines = [
            l.strip() for l in f
            if l.strip() and not l.strip().startswith("#!")
        ]

    if not lines:
        raise SystemExit("[ERROR] run.sh contains no executable commands.")

    if args.slurm:
        print(f"[INFO] Submitting {len(lines)} job(s) to SLURM "
              f"(max in-flight: {MAX_SLURM_JOBS})")
        run_slurm(lines)
    else:
        print(f"[INFO] Running {len(lines)} job(s) locally "
              f"(threads: {PERSONAL_RUN_THREADS})")
        run_personal(lines)


if __name__ == "__main__":
    main()